ktor:
    deployment:
        port: 42081
        watch:
            - classes
            - resources
            - static
    development: true
    application:
        modules:
            - de.noah_ruben.ApplicationKt.module
github:
    mode: "$GITHUB_MODE:wiremock"
    token: "$GITHUB_TOKEN:"
    url: "$GITHUB_URL:"
cv: "${CV_PATH:/Users/i13az81/dev/uni/pers/cv/out/}"
