ktor:
    deployment:
        port: 42081
        watch:
            - classes
            - resources
    development: true
    application:
        modules:
            - de.noah_ruben.ApplicationKt.module
github:
    token: $GITHUB_TOKEN
    url: $GITHUB_URL
