package de.noah_ruben.data.blog

import kotlinx.serialization.encodeToString
import kotlinx.serialization.json.Json
import org.jetbrains.exposed.v1.core.dao.id.EntityID
import org.jetbrains.exposed.v1.dao.IntEntity
import org.jetbrains.exposed.v1.dao.IntEntityClass
import java.time.Instant

class BlogPostEntity(id: EntityID<Int>) : IntEntity(id) {
    companion object : IntEntityClass<BlogPostEntity>(BlogPostTable)

    var slug by BlogPostTable.slug
    var sourcePath by BlogPostTable.sourcePath
    var sourceLastModified by BlogPostTable.sourceLastModified
    var title by BlogPostTable.title
    var summary by BlogPostTable.summary
    var publishedDate by BlogPostTable.publishedDate
    var tagsJson by BlogPostTable.tagsJson
    var excerpt by BlogPostTable.excerpt
    var htmlPath by BlogPostTable.htmlPath
    var htmlLastGenerated by BlogPostTable.htmlLastGenerated
    var isDeleted by BlogPostTable.isDeleted

    fun updateFrom(record: BlogPostRecord) {
        slug = record.slug
        sourcePath = record.sourcePath
        sourceLastModified = record.sourceLastModified
        title = record.title
        summary = record.summary
        publishedDate = record.publishedDate.toString()
        tagsJson = Json.encodeToString(record.tags)
        excerpt = record.excerpt
        htmlPath = record.htmlPath
        htmlLastGenerated = record.htmlLastGenerated
        isDeleted = record.isDeleted
    }

    fun toRecord(): BlogPostRecord = BlogPostRecord(
        slug = slug,
        sourcePath = sourcePath,
        sourceLastModified = sourceLastModified,
        title = title,
        summary = summary,
        publishedDate = Instant.parse(publishedDate),
        tags = Json.decodeFromString(tagsJson),
        excerpt = excerpt,
        htmlPath = htmlPath,
        htmlLastGenerated = htmlLastGenerated,
        isDeleted = isDeleted,
    )
}
