name: Continuous Integration/Testing
"on":
  push:
    branches:
      - main
      - dud
  workflow_dispatch:
concurrency:
  group: "ci"
  cancel-in-progress: true
jobs:
  ktlint:
    runs-on: ubuntu-22.04
    steps:
      - name: Cache Git repository
        id: cache-git-repo-ktlint
        uses: actions/cache@v4
        with:
          path: .git
          key: ${{ runner.os }}-git-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-git-
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 1
      - name: Cache ktlint
        id: cache-ktlint
        uses: actions/cache@v4
        with:
          path: ./ktlint
          key: ${{ runner.os }}-ktlint-1.6.0
      - name: Install ktlint
        if: steps.cache-ktlint.outputs.cache-hit != 'true'
        run: |
          curl -sSLO https://github.com/pinterest/ktlint/releases/download/1.6.0/ktlint
          chmod a+x ktlint
      - name: Run ktlint for job summary
        if: ${{ always() }}
        run: |
          set -o pipefail
          ./ktlint "src/**/*.kt" --reporter=html --editorconfig=".editorconfig" --relative | sed '/<style>/,/<\/style>/d' >> $GITHUB_STEP_SUMMARY
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Cache Git repository
        id: cache-git-repo-test
        uses: actions/cache@v4
        with:
          path: .git
          key: ${{ runner.os }}-git-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-git-
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 1
      - name: Set up GraalVM JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'zulu'
      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Start Wiremock in background
        run: |
          chmod +x wm/wm.sh
          ./wm/wm.sh &
          sleep 5
      - name: Run tests with Gradle
        run: ./gradlew test -x runTailwind -x lintKotlin
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: build/reports/tests/
